[package]
name = "game_of_life"
version = "0.1.0"
authors = ["Fausto Alonso <fnalonso@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
ctrlc = "3.1.4"
structopt = "0.3.15"